// <auto-generated />
using Hazırlık.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hazırlık.Migrations
{
    [DbContext(typeof(HazirlikDBContext))]
    partial class HazırlıkDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hazırlık.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"), 1L, 1);

                    b.Property<string>("OgrenciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinifID")
                        .HasColumnType("int");

                    b.HasKey("OgrenciID");

                    b.HasIndex("SinifID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("Hazırlık.Models.Sinif", b =>
                {
                    b.Property<int>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinifID"), 1L, 1);

                    b.Property<string>("SinifAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SinifKodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinifID");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("Hazırlık.Models.Ogrenci", b =>
                {
                    b.HasOne("Hazırlık.Models.Sinif", "Sinif")
                        .WithMany("ogrencier")
                        .HasForeignKey("SinifID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("Hazırlık.Models.Sinif", b =>
                {
                    b.Navigation("ogrencier");
                });
#pragma warning restore 612, 618
        }
    }
}
